name: Update Codeforces Stats Card

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-card:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate Codeforces card
        run: python scripts/generate_cf_card.py
        
      - name: Update timestamp
        run: date > last-update.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
         git add assets/codeforces-stats.svg last-update.txt
         git commit -m "Auto update Codeforces stats" || echo "No changes"
         git push
